executions:
  execution-title: Smaple Simulation
  execution-class: org.divsgaur.goodload.samples.SampleSimulation
  throughput: 100
  concurrency: 100
  hold-for: 10m
  ramp-up: 5s
  ramp-down: 10s
  iterations:
    - it1:
        dfdsf: dfsfs
        dfsd: dsfds
    - sfds:
        sfd: sfds
