goodload:
  simulations:
    - name: Sample Simulation
      class: org.divsgaur.goodload.samples.SampleSimulation
      throughput: 100
      concurrency: 3
      hold-for: 10m
      ramp-up: 5s
      ramp-down: 10s
      iterations: 5
      enabled: true

    - name: Sample Http Simulation
      class: org.divsgaur.goodload.samples.SampleHttpSimulation
      throughput: 100
      concurrency: 4
      hold-for: 10m
      ramp-up: 5s
      ramp-down: 10s
      iterations: 5
      enabled: true

  reporting:
    include-raw-report: true
    export-directory-path: "./goodload-sample/target/"
    export-formats:
      - "yaml"
      - "json"
      - "json-pretty"

  custom:
    key1: value1
    key2: value2