#######################################################################
# Copyright (C) 2021 Divyansh Shekhar Gaur
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
########################################################################

goodload:
  simulations:
    - name: Sample Simulation
      class: org.goodload.goodload.samples.SampleSimulation
      throughput: 100
      concurrency: 1
      hold-for: 10m
      ramp-up: 5s
      ramp-down: 10s
      iterations: 5
      enabled: false

    - name: Sample Http Simulation
      class: org.goodload.goodload.samples.SampleHttpSimulation
      throughput: 2
      concurrency: 1
      hold-for: 10s
      ramp-up: 5s
      ramp-down: 10s
      iterations: 5
      enabled: true

  fail-when:
    - 5% failures
    - atleast 4 failures
    - atleast x failure

  reporting:
    include-raw-report: false
    export-directory-path: "./goodload-sample/target/"
    export-formats:
      - "yaml"
      - "json"
      - "json-pretty"

  custom:
    http:
      logging:
        request-headers: true

    key1: value1
    key2: value2